"""Home shell markup: two main tabs, widget sources, first-install catalog."""

from __future__ import annotations

import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INDEX = (ROOT / "web" / "index.html").read_text(encoding="utf-8")
TABS = (ROOT / "web" / "js" / "tabs.js").read_text(encoding="utf-8")
HOME_JS = (ROOT / "web" / "js" / "home_layout.js").read_text(encoding="utf-8")
HOME_RUNTIME = (ROOT / "web" / "js" / "home.js").read_text(encoding="utf-8")
GLANCE_TILES = (ROOT / "web" / "js" / "glance_tiles.js").read_text(encoding="utf-8")
TODAY_JS = (ROOT / "web" / "js" / "today.js").read_text(encoding="utf-8")
GLANCE_JS = (ROOT / "web" / "js" / "glance.js").read_text(encoding="utf-8")
CAL_JS = (ROOT / "web" / "js" / "calendar.js").read_text(encoding="utf-8")
UTILS = (ROOT / "web" / "js" / "utils.js").read_text(encoding="utf-8")
SETTINGS_JS = (ROOT / "web" / "js" / "settings.js").read_text(encoding="utf-8")
STYLE = (ROOT / "web" / "style.css").read_text(encoding="utf-8")
SWIFT = (ROOT / "macos" / "KosistenzWindow.swift").read_text(encoding="utf-8")
NATIVE_MAC = (ROOT / "native_mac.py").read_text(encoding="utf-8")
PASTE_JS = (ROOT / "web" / "js" / "paste_insert.js").read_text(encoding="utf-8")


class HomeUiTests(unittest.TestCase):
    def test_sidebar_is_home_journal_and_calendar(self) -> None:
        self.assertIn('data-tab="home"', INDEX)
        self.assertIn('data-tab="journal"', INDEX)
        self.assertIn('data-tab="calendar"', INDEX)
        self.assertIn('data-tab="settings"', INDEX)
        self.assertNotIn('data-tab="today"', INDEX)
        self.assertNotIn('data-tab="workout"', INDEX)
        self.assertNotIn('data-tab="todo"', INDEX)

    def test_old_pages_are_widget_sources(self) -> None:
        for source_id in (
            "todoTab",
            "todayCalendarSource",
            "workoutTab",
            "goalsTab",
            "allWorkTab",
            "analyticsTab",
            "timelineTab",
            "weatherSource",
            "focusSource",
            "countdownSource",
            "habitsSource",
            "heatmapSource",
            "dayBriefSource",
            "countersSource",
            "readingSource",
            "wordTab",
            "clunySource",
            "checklistTab",
        ):
            self.assertIn(f'id="{source_id}"', INDEX)
            self.assertIn("widget-source", INDEX)
        self.assertIn('id="wordCard"', INDEX)
        self.assertIn('id="checklistWizard"', INDEX)
        self.assertIn('id="journalTab"', INDEX)
        self.assertIn('id="journalTab" class="tab-content"', INDEX)

    def test_edit_home_controls_exist(self) -> None:
        for needle in (
            "homeEditBtn",
            "homeGrid",
            "homeGridAbove",
            "homeCheckinBand",
            "homeCheckinBody",
            "homePages",
            "homeAddPageBtn",
            "homeRenamePageBtn",
            "homeCatalog",
        ):
            self.assertIn(f'id="{needle}"', INDEX)

    def test_appearance_color_slots_exist(self) -> None:
        self.assertIn('id="colorSlotList"', INDEX)
        self.assertIn('id="userPresetChips"', INDEX)
        self.assertIn("Saved palettes", INDEX)
        self.assertEqual(INDEX.count('id="inkAutoToggle"'), 1)
        self.assertIn('id="savePresetBtn"', INDEX)
        self.assertIn('id="newPresetBtn"', INDEX)
        self.assertIn('id="inkAutoToggle"', INDEX)
        self.assertIn('id="inkColorInput"', INDEX)
        self.assertNotIn('id="inkCustomWrap"', INDEX)
        self.assertIn('id="accentGrid"', INDEX)
        self.assertIn('data-preset-id', Path(__file__).resolve().parents[1].joinpath("web", "js", "settings.js").read_text(encoding="utf-8"))

    def test_tabs_alias_old_names_to_home(self) -> None:
        self.assertIn("canonicalTab", TABS)
        self.assertIn("today: 'homeTab'", TABS)
        self.assertIn("journal: 'journalTab'", TABS)
        self.assertIn("1: 'home'", TABS)
        self.assertIn("2: 'journal'", TABS)
        self.assertIn("3: 'calendar'", TABS)

    def test_js_catalog_matches_folded_tabs(self) -> None:
        for kind in (
            "todo",
            "today_calendar",
            "workout",
            "goals",
            "allwork",
            "analytics",
            "timeline",
            "weather",
            "focus",
            "countdown",
            "habits",
            "heatmap",
            "day_brief",
            "counters",
            "reading",
            "word",
            "cluny",
            "now_next",
            "unplaced",
            "dues",
            "free_today",
        ):
            self.assertIn(f"{kind}:", HOME_JS)
        self.assertNotIn("journal:", HOME_JS)
        self.assertNotIn("checklist:", HOME_JS)
        self.assertNotIn("settings:", HOME_JS)

    def test_calendar_month_year_markup(self) -> None:
        for needle in ("calViewGroup", "calMonthGrid", "calYearGrid", "calFillWeek", "calPrevWeek"):
            self.assertIn(f'id="{needle}"', INDEX)
        self.assertIn('data-cal-view="week"', INDEX)
        self.assertIn('data-cal-view="month"', INDEX)
        self.assertIn('data-cal-view="year"', INDEX)
        self.assertIn('id="calFillWeek" class="btn-primary"', INDEX)
        self.assertNotIn('id="calFillWeek" class="btn-primary is-hidden"', INDEX)
        self.assertIn('id="calAskCluny"', INDEX)
        self.assertIn("cal-month-legend", STYLE)
        self.assertIn("cal-clock-hint", STYLE)
        self.assertIn("calView = 'week'", CAL_JS)
        self.assertIn("openWeekForDate", CAL_JS)
        self.assertIn("callEel('get_month'", CAL_JS)
        self.assertIn("callEel('get_year'", CAL_JS)
        self.assertIn("callEel('get_week'", CAL_JS)
        self.assertIn("invoke_exposed", (ROOT / "web" / "js" / "lazy.js").read_text(encoding="utf-8"))
        self.assertIn("await loadLayout()", HOME_RUNTIME)
        self.assertIn("data.ok === false", GLANCE_TILES)
        self.assertNotIn("Nothing is written to Apple Calendar", INDEX)
        self.assertNotIn("Month and year for the long view", INDEX)
        self.assertNotIn("Class meeting times live here", INDEX)
        self.assertIn("Nothing to place.", CAL_JS)
        self.assertIn("html[data-page='calendar'] .app-content", STYLE)
        self.assertIn(".cal-month-cell.is-today", STYLE)
        self.assertIn(".cal-month-cell.is-out", STYLE)

    def test_work_layer_markup_and_dismiss_controls(self) -> None:
        for needle in ("homeWorkLayer", "homeWorkBackdrop", "homeWorkPanel", "homeWorkTitle", "homeWorkClose", "homeWorkBody"):
            self.assertIn(f'id="{needle}"', INDEX)
        self.assertIn("home-work-layer", STYLE)
        self.assertIn("home-work-backdrop", STYLE)
        self.assertIn("applyPanelBox", HOME_RUNTIME)
        self.assertIn("is-source", HOME_RUNTIME)
        self.assertIn("tileBox", HOME_RUNTIME)
        self.assertIn("openHomeWork", HOME_RUNTIME)
        self.assertIn("closeHomeWork", HOME_RUNTIME)
        self.assertIn("homeWorkClose", HOME_RUNTIME)
        self.assertIn("homeWorkBackdrop", HOME_RUNTIME)
        begin = HOME_RUNTIME.split("const beginDrag")[1].split("const beginResize")[0]
        self.assertIn("if (!editing) return", begin)
        self.assertIn("openHomeWork(card.getAttribute('data-kind')", HOME_RUNTIME)
        self.assertIn("Escape", HOME_RUNTIME)
        self.assertIn("w-weather", HOME_RUNTIME)
        self.assertIn("w-word", HOME_RUNTIME)
        self.assertIn("inert", HOME_RUNTIME)

    def test_glances_mount_instead_of_full_pages(self) -> None:
        self.assertIn("mountGlance", HOME_RUNTIME)
        self.assertIn("from './glance_tiles.js'", HOME_RUNTIME)
        self.assertNotIn("mountWidget(", HOME_RUNTIME)
        self.assertIn("export function mountGlance", GLANCE_TILES)
        self.assertIn("function weatherHtml", GLANCE_TILES)
        self.assertIn("function wordHtml", GLANCE_TILES)
        self.assertIn("function todayHtml", GLANCE_TILES)
        self.assertIn("function todoHtml", GLANCE_TILES)
        self.assertIn("function countdownHtml", GLANCE_TILES)
        self.assertIn("function readingHtml", GLANCE_TILES)
        self.assertIn("function workoutHtml", GLANCE_TILES)
        self.assertIn("function goalsHtml", GLANCE_TILES)
        self.assertIn("function allworkHtml", GLANCE_TILES)
        self.assertIn("function heatmapHtml", GLANCE_TILES)
        self.assertIn("function dayBriefHtml", GLANCE_TILES)
        self.assertIn("function analyticsHtml", GLANCE_TILES)
        self.assertIn("function timelineHtml", GLANCE_TILES)
        self.assertIn("function posterHtml", GLANCE_TILES)
        self.assertIn("function shellHtml", GLANCE_TILES)
        self.assertIn("glance_copy.js", GLANCE_TILES)
        self.assertIn("get_work_board", GLANCE_TILES)
        self.assertIn("get_today_home", GLANCE_TILES)
        self.assertIn("get_weather_forecast", GLANCE_TILES)
        self.assertIn("get_word_of_the_day", GLANCE_TILES)
        self.assertIn("get_heatmap", GLANCE_TILES)
        self.assertIn("get_analytics", GLANCE_TILES)
        self.assertIn("get_timeline_day", GLANCE_TILES)
        self.assertIn("get_cluny_inbox", GLANCE_TILES)
        self.assertIn("function clunyHtml", GLANCE_TILES)
        self.assertIn("function nowNextHtml", GLANCE_TILES)
        self.assertIn("function unplacedHtml", GLANCE_TILES)
        self.assertIn("function duesHtml", GLANCE_TILES)
        self.assertIn("function freeTodayHtml", GLANCE_TILES)
        self.assertIn("todo-plus15", GLANCE_TILES)
        self.assertIn("work-today", GLANCE_TILES)
        self.assertIn("block-skip", GLANCE_TILES)
        self.assertIn("workout-log", GLANCE_TILES)
        self.assertIn("get_now_next_glance", GLANCE_TILES)
        self.assertNotIn("The days in a row", GLANCE_TILES)
        self.assertNotIn("A year at a glance", GLANCE_TILES)
        self.assertNotIn("The book in your hands", GLANCE_TILES)
        self.assertNotIn("Tick the small things", INDEX)
        self.assertNotIn("How this works", INDEX)
        self.assertNotIn("Forecast stays cached on this Mac", INDEX)
        self.assertNotIn("Name the work and how long it takes", INDEX)
        self.assertNotIn("Log body weight and today’s sessions", INDEX)
        self.assertIn(".glance-tile", STYLE)
        self.assertIn(".glance-kpi", STYLE)
        self.assertIn(".home-work-body > .widget-source", STYLE)
        self.assertIn("data-glance-act", GLANCE_TILES)
        self.assertIn("runGlanceAction", GLANCE_TILES)
        self.assertIn("keep_daily_focus", GLANCE_TILES)
        self.assertIn("todo-finish", GLANCE_TILES)
        self.assertIn("habit-tick", GLANCE_TILES)
        self.assertIn("counter-tap", GLANCE_TILES)
        self.assertIn("focus-keep", GLANCE_TILES)
        self.assertIn("dayPart", GLANCE_TILES)
        self.assertIn("syncHomeDayPart", HOME_RUNTIME)
        self.assertIn(".glance-action", STYLE)
        self.assertIn(".glance-label", STYLE)
        self.assertIn(".home-widget.is-source", STYLE)
        self.assertNotIn("on the clock", GLANCE_TILES)
        self.assertNotIn("waiting to be dated", GLANCE_TILES)
        self.assertIn("1 event today.", (ROOT / "web" / "js" / "glance_copy.js").read_text(encoding="utf-8"))
        self.assertIn("clunyOff: 'Off'", (ROOT / "web" / "js" / "glance_copy.js").read_text(encoding="utf-8"))
        self.assertIn("noBrief: 'No brief yet'", (ROOT / "web" / "js" / "glance_copy.js").read_text(encoding="utf-8"))
        self.assertIn("unscheduled", (ROOT / "web" / "js" / "glance_copy.js").read_text(encoding="utf-8"))

    def test_live_home_opens_work_edit_home_moves(self) -> None:
        self.assertIn("home-live-copy", INDEX)
        self.assertIn("home-widget-handle", HOME_RUNTIME)
        self.assertIn("closest('.home-widget-chrome')", HOME_RUNTIME)
        self.assertIn("closest('.home-widget-body')", HOME_RUNTIME)
        self.assertIn("window.addEventListener('pointermove', moveDrag)", HOME_RUNTIME)
        self.assertIn("window.addEventListener('mousemove', moveDrag)", HOME_RUNTIME)
        begin = HOME_RUNTIME.split("const beginDrag")[1].split("const moveDrag")[0]
        self.assertIn("if (!editing) return", begin)
        self.assertIn("openHomeWork", HOME_RUNTIME.split("addEventListener('click'")[-1].split("const beginDrag")[0])
        self.assertIn("runGlanceAction", HOME_RUNTIME)
        self.assertIn("data-glance-act", HOME_RUNTIME)

    def test_home_widgets_resize_by_dragging_handles(self) -> None:
        self.assertIn("export function pickResize", HOME_JS)
        self.assertIn('data-resize="se"', HOME_RUNTIME)
        self.assertIn('data-resize="e"', HOME_RUNTIME)
        self.assertIn('data-resize="s"', HOME_RUNTIME)
        self.assertNotIn('data-act="resize"', HOME_RUNTIME)
        self.assertNotIn(">Size</button>", HOME_RUNTIME)
        self.assertIn("eel.resize_home_widget(page.id, id, w | 0, h | 0)", HOME_RUNTIME)
        self.assertIn("beginResize", HOME_RUNTIME)
        self.assertIn("cursor: nwse-resize", STYLE)
        self.assertIn("Drag a corner or edge", INDEX)

    def test_home_widget_refresh_continues_after_one_failure(self) -> None:
        refresh = HOME_RUNTIME.split("async function refreshKinds")[1].split("function paintPages")[0]
        self.assertIn("const run = async (fn)", refresh)
        self.assertIn("await run(refresh)", refresh)
        self.assertIn("refreshGlances", refresh)
        self.assertIn("ensureWork", HOME_RUNTIME)
        self.assertIn("console.error(err)", refresh)

    def test_native_prompts_use_in_app_dialog(self) -> None:
        self.assertIn('id="appDialog"', INDEX)
        self.assertIn("export function askText", UTILS)
        self.assertIn("export function askConfirm", UTILS)
        self.assertIn("utils.askText", HOME_RUNTIME)
        self.assertIn("utils.askConfirm", HOME_RUNTIME)
        self.assertNotIn("window.prompt", HOME_RUNTIME)
        self.assertNotIn("window.confirm", HOME_RUNTIME)
        self.assertIn("utils.askText", SETTINGS_JS)
        self.assertIn("utils.askConfirm", SETTINGS_JS)
        self.assertNotIn("window.prompt", SETTINGS_JS)
        self.assertNotIn("window.confirm", SETTINGS_JS)

    def test_webkit_hosts_implement_js_dialogs(self) -> None:
        self.assertIn("webView.uiDelegate = self", SWIFT)
        self.assertIn("runJavaScriptTextInputPanelWithPrompt", SWIFT)
        self.assertIn("setUIDelegate_", NATIVE_MAC)
        self.assertIn("runJavaScriptTextInputPanelWithPrompt", NATIVE_MAC)

    def test_calendar_ics_paste_inserts_url_instead_of_navigating(self) -> None:
        self.assertIn('<input type="text" id="calIcsUrl"', INDEX)
        self.assertIn("js/paste_insert.js", INDEX)
        self.assertIn("window.kosistenzInsertText", PASTE_JS)
        self.assertIn("kosistenzSanitizePastedUrl", PASTE_JS)
        self.assertIn("class KosistenzWebView", SWIFT)
        self.assertIn("pasteboardURLText", SWIFT)
        self.assertIn("pasteboardIcsText", SWIFT)
        self.assertIn("pasteCalendarPayload", SWIFT)
        self.assertIn('type == "icsPaste"', SWIFT)
        self.assertIn("NSSelectorFromString", SWIFT)
        self.assertIn("performWebEdit", SWIFT)
        self.assertIn('performWebEdit("copy:", on: hostWebView)', SWIFT)
        self.assertNotIn("#selector(NSResponder.", SWIFT)
        self.assertNotIn("NSResponder.paste", SWIFT)
        self.assertNotIn("NSResponder.copy", SWIFT)
        self.assertNotIn("NSResponder.cut", SWIFT)
        self.assertNotIn("NSResponder.selectAll", SWIFT)
        self.assertNotIn("hostWebView?.copy(", SWIFT)
        self.assertNotIn("webView?.copy(", SWIFT)
        self.assertNotIn("webView?.cut(", SWIFT)
        self.assertNotIn("webView?.paste(", SWIFT)
        self.assertIn("pasteFromClipboard", SWIFT)
        self.assertIn("extractURL", SWIFT)
        self.assertIn("makeFirstResponder", SWIFT)
        self.assertIn("pastePlainStringThroughWebKit", SWIFT)
        self.assertIn("class KosistenzMainWindow", SWIFT)
        self.assertIn("if let process = self.bridge, !process.isRunning", SWIFT)
        self.assertIn("process.terminationStatus", SWIFT)
        self.assertNotIn("bridge?.terminationStatus", SWIFT)
        widget = (ROOT / "macos" / "KosistenzWidget.swift").read_text(encoding="utf-8")
        self.assertIn("#if os(iOS)", widget)
        self.assertNotIn("if #available(macOS 14.0, *)", widget)
        self.assertIn("enum KosistenzApp", SWIFT)
        self.assertNotIn("self?.waitForHTTP", SWIFT)
        self.assertNotIn("super.paste", SWIFT)
        self.assertIn("override func sendEvent", SWIFT)
        self.assertIn("htmlString(from", SWIFT)
        self.assertIn("hostWebView", SWIFT)
        build_app = (ROOT / "build_app.py").read_text(encoding="utf-8")
        self.assertIn('"-parse-as-library"', build_app)
        self.assertIn('"-parse-as-library",\n        "-o", python_exe', build_app)
        chrome = (ROOT / "macos" / "KosistenzChrome.swift").read_text(encoding="utf-8")
        self.assertIn("window.toolbar = nil", chrome)
        self.assertNotIn("todayWorkout", chrome)
        self.assertNotIn("toolbarOpenToday", chrome)
        self.assertNotIn("NSToolbarDelegate", SWIFT)
        self.assertIn("origin.port == 0", chrome)
        self.assertNotIn("navigationAction.navigationType == .other", SWIFT)
        self.assertIn("kosistenzLooksLikeCalendarUrl", PASTE_JS)
        self.assertIn("looksLikeCalendarUrl", PASTE_JS)
        self.assertIn("isCalendarPage", PASTE_JS)
        self.assertIn("addEventListener('paste'", PASTE_JS)
        self.assertIn("performKeyEquivalent_", NATIVE_MAC)
        self.assertIn("class PasteWindow", NATIVE_MAC)
        self.assertIn("sendEvent_", NATIVE_MAC)
        self.assertNotIn('type="datetime-local"', INDEX)
        self.assertIn('placeholder="2026-09-08 0930"', INDEX)
        self.assertIn("fromLocalInput", CAL_JS)
        calendar_swift = (ROOT / "macos" / "KosistenzCalendar.swift").read_text(encoding="utf-8")
        self.assertIn("timeoutInterval: 120", calendar_swift)
        self.assertIn("addEventListener('paste'", CAL_JS)
        self.assertIn("kosistenzSanitizePastedUrl", CAL_JS)
        self.assertIn("clockWindow", CAL_JS)
        self.assertIn("minutesFromClock", CAL_JS)
        self.assertIn("saveAwake", CAL_JS)
        self.assertIn("import_pasted_calendar", CAL_JS)
        self.assertIn("pasteIcsButton", CAL_JS)
        self.assertIn("cal-hour-line", CAL_JS)
        self.assertIn('id="calPasteIcs"', INDEX)
        self.assertIn('id="calDayStart"', INDEX)
        self.assertIn('id="calDayEnd"', INDEX)
        self.assertIn('placeholder="0530"', INDEX)
        self.assertIn('placeholder="2130"', INDEX)
        self.assertIn("cal-hour-line", STYLE)
        self.assertNotIn("hourRange", CAL_JS)
        self.assertIn('id="calSaveItem"', INDEX)
        self.assertIn('id="calParkItem"', INDEX)
        self.assertIn("Save for later", INDEX)
        self.assertIn("update_calendar_event", CAL_JS)
        self.assertIn("park_schedule_block", CAL_JS)
        self.assertIn("schedule_work_at", CAL_JS)
        self.assertIn("onBlockPointerMove", CAL_JS)
        self.assertIn("unplaced_total", CAL_JS)
        self.assertIn("cal-due-chip", CAL_JS)
        self.assertIn("day.dues", CAL_JS)
        self.assertIn("renderDueStrip", CAL_JS)
        self.assertIn("shortTitle", CAL_JS)
        self.assertIn("dueParts", CAL_JS)
        self.assertIn("cal-week-board", CAL_JS)
        self.assertIn("cal-due-strip", CAL_JS)
        self.assertIn("showDayDues", CAL_JS)
        self.assertIn("hideDayDues", CAL_JS)
        self.assertIn("cal-block-time", CAL_JS)
        self.assertIn("replace(/^webcal:/i, 'https:')", CAL_JS)
        self.assertNotIn("dues.slice(0, 8)", CAL_JS)
        self.assertIn("grid-template-rows: subgrid", STYLE)
        self.assertIn("grid-row: 1 / span 3", STYLE)
        self.assertIn("cal-week-board", STYLE)
        self.assertIn("cal-course-badge", STYLE)
        self.assertNotIn("max-height: 2.75rem", STYLE)
        self.assertNotIn("padding-top: calc(36px + 2.75rem)", STYLE)
        self.assertNotIn("min-height: 560px", STYLE)
        self.assertIn('id="calendarFeedsList"', INDEX)
        self.assertIn("unsubscribe_calendar_feed", SETTINGS_JS)
        self.assertNotIn('id="deleteUndatedImportsBtn"', INDEX)
        self.assertNotIn('id="allWorkDeleteUndated"', INDEX)
        self.assertNotIn('id="calDeleteUndated"', INDEX)
        self.assertIn('id="calTodayRail"', INDEX)
        self.assertIn('id="calDayDues"', INDEX)
        self.assertIn("cal-feeds-panel", INDEX)
        self.assertIn('id="calFeedToggles"', INDEX)
        self.assertIn('id="calDueMenu"', INDEX)
        self.assertIn("renderDueChip", CAL_JS)
        self.assertIn("place_work_after_lecture", CAL_JS)
        self.assertIn("Add to calendar", INDEX)
        self.assertIn("Add another", INDEX)
        self.assertIn("Place after this", INDEX)
        self.assertNotIn("New lecture", INDEX)
        self.assertNotIn("Place after lecture", INDEX)
        self.assertIn("selectedEventDays", CAL_JS)
        self.assertIn("set_calendar_feed_enabled", CAL_JS)
        self.assertIn("--due-h", CAL_JS)
        self.assertIn("kosistenz:open-todo", CAL_JS)
        self.assertIn("Open in To Do", INDEX)
        self.assertIn("data-feed-enabled", SETTINGS_JS)

    def test_calendar_tab_uses_full_width_and_taller_cells(self) -> None:
        self.assertIn("html[data-page='calendar'] .tab-content.active", STYLE)
        self.assertIn("max-width: none", STYLE)
        self.assertIn("min-height: 4.5rem", STYLE)
        self.assertIn("minmax(0, 1fr) minmax(240px, 280px)", STYLE)

    def test_home_shows_page_title_and_sidebar_pages(self) -> None:
        self.assertIn('id="homePageTitle"', INDEX)
        self.assertIn("home-title-strip", INDEX)
        self.assertIn('id="homeNavPages"', INDEX)
        self.assertIn("data-home-page", HOME_RUNTIME)
        self.assertIn("paintSidebar", HOME_RUNTIME)
        self.assertIn("homePageId", TABS)
        self.assertIn("clearHomePageColors", TABS)

    def test_per_page_colors_and_settings_board(self) -> None:
        self.assertIn('id="colorScopeGroup"', INDEX)
        self.assertIn('data-color-scope="page"', INDEX)
        self.assertIn('id="colorPageSelect"', INDEX)
        self.assertIn("set_home_page_colors", SETTINGS_JS)
        self.assertIn("applyAppearanceOverlay", HOME_RUNTIME)
        self.assertIn('id="settingsBoard"', INDEX)
        self.assertIn('data-settings-col="cluny"', INDEX)
        self.assertIn('id="clunySqlitePath"', INDEX)
        self.assertIn('id="clunySaveBtn"', INDEX)
        self.assertIn("settings-resize", INDEX)
        self.assertIn("html[data-page='settings'] .tab-content.active", STYLE)
        self.assertIn("cursor: col-resize", STYLE)
        self.assertIn("setupSettingsResize", SETTINGS_JS)
        self.assertIn("saveClunySettings", SETTINGS_JS)
        self.assertIn("clunyBrainUrl", SETTINGS_JS)
        self.assertIn("probe_cluny_connection", SETTINGS_JS)
        self.assertIn("setPageColorSlot", SETTINGS_JS)

    def test_home_widgets_are_dense_and_scroll_the_page(self) -> None:
        self.assertIn("--home-row: var(--row-h, 88px)", STYLE)
        self.assertIn("grid-auto-rows: var(--home-row)", STYLE)
        self.assertIn("min-height: 0", STYLE)
        self.assertIn("overflow-y: auto", STYLE)
        self.assertIn("padding-bottom: 88px", STYLE)
        self.assertIn('sizes: [[1, 1]', HOME_JS)
        self.assertIn("default: [2, 2]", HOME_JS)
        self.assertIn("default: [2, 1]", HOME_JS)
        self.assertIn('[data-w="1"][data-h="1"]', STYLE)
        self.assertIn(".home-widget-chrome", STYLE)
        self.assertIn("countdown-days", GLANCE_JS)
        tokens = (ROOT / "web" / "tokens.css").read_text(encoding="utf-8")
        self.assertIn("--row-h: 108px", tokens)
        self.assertIn("--line:", tokens)
        self.assertIn('href="tokens.css"', INDEX)
        self.assertIn("max-width: 1440px", STYLE)
        self.assertNotIn("html[data-page='home'] .tab-content.active {\n    max-width: none", STYLE)

    def test_today_mini_widget_loads_without_legacy_today_page(self) -> None:
        self.assertIn('id="todayCalendarSource"', INDEX)
        self.assertIn('id="todayDateTitle"', INDEX)
        self.assertIn('id="todayAgenda"', INDEX)
        self.assertNotIn('id="todayHome"', INDEX)
        self.assertIn("getElementById('todayCalendarSource')", TODAY_JS)
        self.assertNotIn("getElementById('todayHome')", TODAY_JS)
        self.assertNotIn("paintCustomize()", TODAY_JS)
        self.assertIn("get_home_boot", HOME_RUNTIME)
        self.assertNotIn("loadLayout().then(() => renderHome())", HOME_RUNTIME)
        self.assertIn("weather-place-form.is-collapsed", STYLE)
        self.assertIn("pointer-events: none", STYLE)

    def test_app_opens_home_without_startup_delays(self) -> None:
        app = (ROOT / "web" / "app.js").read_text(encoding="utf-8")
        bridge = (ROOT / "bridge.py").read_text(encoding="utf-8")
        self.assertNotIn("setTimeout(resolve, 100)", app)
        self.assertNotIn("setTimeout(() => init().catch(handleInitError), 50)", app)
        self.assertNotIn("from './js/calendar.js'", app)
        self.assertNotIn("from './js/journal.js'", app)
        self.assertIn("void pullPhoneOnOpen()", app)
        self.assertNotIn("await pullPhoneOnOpen()", app)
        self.assertNotIn("maybe_pull_icloud_on_open()", bridge)
        self.assertIn("register_lazy_exposes()", bridge)
        self.assertNotIn("import calclock", bridge)
        self.assertNotIn("import brain", bridge)
        boot = (ROOT / "home_boot.py").read_text(encoding="utf-8")
        self.assertIn("start_supervisor", boot)
        self.assertIn("get_home_boot", boot)
        tabs = (ROOT / "web" / "js" / "tabs.js").read_text(encoding="utf-8")
        self.assertIn("import('./calendar.js')", tabs)
        self.assertIn("bootFeature", tabs)

    def test_journal_tab_and_first_page_checkin_band(self) -> None:
        app = (ROOT / "web" / "app.js").read_text(encoding="utf-8")
        journal = (ROOT / "web" / "js" / "journal.js").read_text(encoding="utf-8")
        self.assertIn("switchTab('journal')", app)
        self.assertNotIn("ensureHomeWidget('journal')", app)
        self.assertIn("tab?.classList.contains('active')", journal)
        self.assertIn('id="homeBoard"', INDEX)
        self.assertIn('id="homeGridAbove"', INDEX)
        self.assertIn('id="homeCheckinBand"', INDEX)
        self.assertIn('id="homeCheckinToggle"', INDEX)
        self.assertIn('id="homeCheckinOther"', INDEX)
        self.assertIn("syncCheckin", HOME_RUNTIME)
        checklist = (ROOT / "web" / "js" / "daily_checklist.js").read_text(encoding="utf-8")
        self.assertIn("checklistSetupBound", checklist)
        self.assertIn("callEel('get_daily_checklist')", checklist)
        self.assertIn(".home-pages {\n    display: none;", STYLE)
        self.assertIn("dropRegion", HOME_RUNTIME)
        self.assertIn("homeCheckinBand", HOME_RUNTIME)
        self.assertIn("open-evening-checkin", HOME_RUNTIME)
        self.assertNotIn("ensureHomeWidget('checklist')", HOME_RUNTIME)
        self.assertIn("home-checkin-band", STYLE)
        self.assertIn("is-empty-drop", STYLE)
        self.assertIn("html[data-page='journal'] .tab-content.active", STYLE)
        self.assertIn('class="journal-compose journal-paper"', INDEX)
        self.assertNotIn("panel journal-compose", INDEX)
        self.assertNotIn("journal-compose journal-paper panel", INDEX)
        self.assertNotIn("Last 30 days", INDEX)
        self.assertIn("Nothing saved this month.", journal)
        self.assertIn("empty-state--line", journal)
        self.assertIn("empty-state--line", STYLE)
        self.assertNotIn("On this Mac", INDEX)
        self.assertIn(".brand-tag", STYLE)
        self.assertIn('data-sidebar="compact"', INDEX)
        self.assertIn('aria-label="Expand sidebar"', INDEX)

    def test_cluny_ask_widget_and_day_hook(self) -> None:
        app = (ROOT / "web" / "app.js").read_text(encoding="utf-8")
        cluny = (ROOT / "web" / "js" / "cluny.js").read_text(encoding="utf-8")
        day = (ROOT / "web" / "js" / "day_brief.js").read_text(encoding="utf-8")
        self.assertIn('id="clunySource"', INDEX)
        self.assertIn('id="clunyAskForm"', INDEX)
        self.assertIn('id="clunyInbox"', INDEX)
        self.assertIn('id="clunyBrainUrl"', INDEX)
        self.assertIn('id="clunyTestBtn"', INDEX)
        self.assertIn('id="dayBriefCluny"', INDEX)
        self.assertIn("import('./cluny.js')", HOME_RUNTIME)
        self.assertIn("ensureWork", HOME_RUNTIME)
        self.assertIn("kosistenz:open-cluny", HOME_RUNTIME)
        self.assertIn("ensureHomeWidget('cluny')", HOME_RUNTIME)
        self.assertNotIn("ensureHomeWidget('journal')", HOME_RUNTIME)
        self.assertIn("ask_cluny", cluny)
        self.assertIn("accept_cluny_proposal", cluny)
        self.assertIn("dayBriefOpenCluny", day)
        self.assertIn("kosistenz:open-cluny", day)
        self.assertIn("cluny-chip", STYLE)
        self.assertIn("kind === 'cluny'", GLANCE_TILES)
        self.assertIn('data-cluny-prompt="What do I have to do today?"', INDEX)
        self.assertIn('data-cluny-prompt="What should I do with my free time?"', INDEX)
        self.assertIn("promptCluny", cluny)
        self.assertIn("promptCluny", HOME_RUNTIME)
        self.assertIn("cluny-ask", GLANCE_TILES)
        self.assertIn("w-cluny", HOME_RUNTIME)
        self.assertIn("local-week", HOME_RUNTIME)
        self.assertIn("name: 'Week'", HOME_RUNTIME)
        self.assertIn("eveningAsk", (ROOT / "web" / "js" / "glance_copy.js").read_text(encoding="utf-8"))
        self.assertIn("What still matters tonight?", GLANCE_TILES)
        self.assertIn("Asking Cluny…", cluny)
        self.assertIn("brain_ready === false", GLANCE_TILES)
        self.assertIn('id="clunyBackfillBtn"', INDEX)
        self.assertIn('id="clunyBackfillLifeBtn"', INDEX)
        self.assertIn("backfill_cluny_journals", SETTINGS_JS)
        self.assertIn("backfill_cluny_life", SETTINGS_JS)
        self.assertIn("Index my life", INDEX)
        self.assertIn("Ask about what you wrote", INDEX)
        self.assertIn("Cluny does not schedule", INDEX)
        self.assertIn("never an HH:MM", INDEX)
        self.assertIn("Indexed PDFs and notes", INDEX)
        self.assertIn('id="libraryOffline"', INDEX)
        self.assertIn('option value="propose"', INDEX)
        self.assertNotIn('option value="planner"', INDEX)
        self.assertIn("Kosistenz keeps the list and the clock", INDEX)
        self.assertIn("/opt/homebrew/bin", INDEX)
        self.assertIn('id="clunySnapshotStatus"', INDEX)
        self.assertIn("backfill_cluny_journals", SETTINGS_JS)
        self.assertIn("class=\"todo-more\"", INDEX)
        self.assertIn("Do this week", INDEX)
        self.assertIn("Repeat on these days", INDEX)
        self.assertIn("Add to today", INDEX)
        self.assertIn("Save repeating to-do", (ROOT / "web" / "js" / "todo.js").read_text(encoding="utf-8"))
        self.assertIn("⌘</kbd><kbd>1</kbd> Home", INDEX)
